@extends('layouts.app')
@section('title', 'Doctor Info')
@section('content')

@if (session()->has('success'))
<script>
    window.onload = () => {
        Swal.fire({
            position: "top",
            toast: true,
            showConfirmButton: false,
            timer: 2000,
            timerProgressBar: true,
            icon: "success",
            title: "{{session()->get('success')}}"
        });
    }
</script>
@endif

<div class="content-wrapper">
    <div class="container-fluid">

        <article class="d-flex align-items-center  justify-content-between gap-5 mb-4">
            <h4 class="top-heading mb-0">Doctor Info</h4>
            <a href="{{route('show_edit_form',$doctor_info->docid )}}" class="btn btn-success p-2"><i class="fa fa-edit"></i> Update </a>
        </article>
        @if ($errors->any())
        <div class="text-center">
            @foreach ($errors->all() as $error)
            <p class="alert alert-danger">{{ $error }}</p>
            @endforeach
        </div>
        @endif
        <div class="record-container" style="background-color: var(--outgoing-bg); color:var(--txt-color);">

            <!-- Header -->
            <div class="header-section d-flex justify-content-between align-items-start flex-wrap">
                <div>
                    <i class="fa fa-user-alt fa-3x"></i>
                    <div class="record-title">Doctor Information</div>
                    <small>Made by Computer</small>
                </div>
                <div class="file-info mt-3 mt-md-0">
                    <p class="text"><strong>File Number:</strong> #1234567-890</p>
                    <p><strong>Record ID:</strong> E998A742</p>
                    <p><small>Generated by the State Computer</small></p>
                </div>
            </div>

            <!-- Personal Info -->
            <div class="row g-3">
                <div class="col-lg-8">
                    <table class="table table-borderless">
                        <tbody>
                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Name</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">{{$doctor_info->name}}</td>
                            </tr>

                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Email</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">{{$doctor_info->email}}</td>
                            </tr>

                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Contact</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">{{$doctor_info->contact}}</td>

                            </tr>
                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Specialty</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">{{$doctor_info->specialty->sname}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="col-lg-4">

                    @if (!$doctor_info->image)

                    <div class=""><img src="{{ asset('assets/svg/doctor-svgrepo-com.svg') }}" class="profile-photo" alt=""></div>
                    @else
                    <div class=""><img src="{{ asset('uploads/doctors/' . $doctor_info->image) }}" class="profile-photo" alt=""></div>
                    @endif


                </div>
            </div>

            <!-- Arrest Info -->
            <div class="section-title">Today's Appointment </div>
            <div class="table-responsive">
                <table id="usersTable" class="dashboard-table table align-middle table-hover border">
                    <thead class="table-light">
                        <tr>
                            <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Date</th>
                            <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Session Title</th>
                            <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Institution</th>
                            <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Patient</th>
                            <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($appointments as $appointment)
                        <tr>
                            <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">{{\Carbon\Carbon::parse($appointment->appodate)->format('M d, Y')}}</td>
                            <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">{{$appointment->schedule->title}}</td>
                            <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">Campus Health Services</td>
                            <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">{{$appointment->patient->name}}</td>
                            <td style="background-color: var(--outgoing-bg); color:var(--txt-color);" class="text-capitalize">{{$appointment->status}}</td>
                        </tr>
                        @empty

                        @endforelse
                    </tbody>
                </table>
            </div>

            <!-- Fingerprints and Other Info -->
            <div class="row mt-3">
                <div class="col-md-6">
                    <div class="section-title">Fingerprints</div>
                    <div class="fingerprints d-flex flex-wrap">
                        <i class="fa fa-fingerprint"></i><i class="fa fa-fingerprint"></i><i class="fa fa-fingerprint"></i><i class="fa fa-fingerprint"></i><i class="fa fa-fingerprint"></i>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="section-title">Biography</div>
                    <p class="footer-note text">
                        {{$doctor_info->bio->biography ?? 'No Bio'}}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script>
    $(document).ready(function() {
        const table = $('#usersTable').DataTable({
            scrollX: false,
            pagingType: 'simple_numbers',
            pageLength: 2,  
            lengthMenu: [2, 10, 25, 50, 100],
            dom: 'rt<"d-flex justify-content-between align-items-center p-2"lip>',
            columnDefs: [{
                orderable: false,
                targets: [1, 2, 3] // Make columns 1, 2, and 3 not orderable
            }, {
                type: 'num',
                targets: 0 // Treat the first column as numbers
            }],
            order: [
                [0, 'asc']
            ], // Order by the first column in ascending order
        });
        $('#tableSearch').on('keyup', function() {
            table.search(this.value).draw();
        });
    });
</script>
@endsection