@extends('layouts.app')
@section('title', 'Update Doctor Info')
@section('content')
<section class="content-wrapper">
    <form action="{{ route('update_doctor', $doctor_info->docid) }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="record-container" style="background-color: var(--outgoing-bg); color:var(--txt-color);">
            <!-- Header -->
            <div class="header-section d-flex justify-content-between align-items-start flex-wrap">
                <div>
                    <i class="fa fa-user-alt fa-3x"></i>
                    <div class="record-title">Update Doctor Information</div>
                    <small>Made by Computer</small>
                </div>
                <div class="file-info mt-3 mt-md-0">
                    <p><strong>File Number:</strong> #1234567-890</p>
                    <p><strong>Record ID:</strong> E998A742</p>
                    <p><small>Generated by the State Computer</small></p>
                </div>

            </div>

            <!-- Personal Info -->
            <div class="row g-3">
                <div class="col-lg-8">
                    <table class="table table-borderless">
                        <tbody>
                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);"> Name</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);"><input class="form-control" type="text" name="name" value="{{$doctor_info->name}}" spellcheck="false"></td>
                            </tr>

                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Email</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);"><input class="form-control" type="email" name="email" value="{{$doctor_info->email}}" spellcheck="false"></td>

                            </tr>
                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Contact</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">
                                    <input class="form-control" type="tel" name="contact" maxlength="11" pattern="[0-9]{11}" value="{{$doctor_info->contact}}" spellcheck="false">
                                </td>
                            </tr>
                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Expertise</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">
                                    <select name="specialties" class="form-control form-select" id="">
                                        <option value="{{$doctor_info->specialty->id}}">{{$doctor_info->specialty->sname}}</option>

                                        @foreach ($specialties as $spe)
                                        <option value="{{$spe->id}}">{{$spe->sname}}</option>
                                        @endforeach
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Bio</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">
                                    <textarea name="biography" id="biography" class="form-control text-start" rows="5" style="resize: none;">
                                    {{$doctor_info->bio->biography ?? 'No Bio'}}
                                    </textarea>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="col-lg-4">

                    @if (!$doctor_info->image)
                    <div class=""><img src="{{ asset('assets/svg/doctor-svgrepo-com.svg')}}" class="preview profile-photo" alt=""></div>
                    @else
                    <div class=""><img src="{{ asset('uploads/doctors/' . $doctor_info->image)}}" class="preview profile-photo" alt=""></div>
                    @endif

                    <label for="image">Upload image</label>
                    <input type="file" id="imageInput" class="form-control" name="image" accept="image/*" onchange="previewImage(event)">


                </div>
            </div>

            <button class="btn btn-primary btn-lg">Update</button>

        </div>

        @if ($errors->any())
        <div class="text-center mt-4">
            @foreach ($errors->all() as $error)
            <p class="alert alert-danger">{{ $error }}</p>
            @endforeach
        </div>
        @endif
    </form>

</section>
<script>
    document.getElementById("imageInput").onchange = function(event) {
        const [file] = event.target.files;
        if (file) {
            const preview = document.querySelector(".preview");
            preview.src = URL.createObjectURL(file);
            preview.style.display = "block";

        }
    };
</script>

@endsection