@extends('layouts.app')
@section('title', 'Patient Info')
@section('content')
@if (session()->has('success'))
<script>
    window.onload = () => {
        Swal.fire({
            position: "top",
            toast: true,
            showConfirmButton: false,
            timer: 2000,
            timerProgressBar: true,
            icon: "success",
            title: "{{session()->get('success')}}"
        });
    }
</script>
@endif
@if ($errors->any())
<div class="text-center">
    @foreach ($errors->all() as $error)
    <p class="alert alert-danger">{{ $error }}</p>
    @endforeach
</div>
@endif
<div class="content-wrapper">
    <div class="record-container" style="background-color: var(--outgoing-bg); color:var(--txt-color);">
        <!-- Header -->
        <div class="header-section d-flex justify-content-between align-items-start flex-wrap">
            <div>
                <i class="fa fa-user-alt fa-3x"></i>
                <div class="record-title">Patient Information</div>
                <small>Made by Computer</small>
            </div>
            <div class="file-info mt-3 mt-md-0">
                <p><strong>File Number:</strong> #1234567-890</p>
                <p><strong>Record ID:</strong> E998A742</p>
                <p><small>Generated by the State Computer</small></p>
            </div>
        </div>

        <!-- Personal Info -->
        <div class="row g-3">
            <div class="col-lg-8">
                <table class="table table-borderless">
                    <tbody>
                        <tr>
                            <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Name</th>
                            <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">{{$patient->name}}</td>
                        </tr>

                        <tr>
                            <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Gender</th>
                            <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">{{$patient->gender?? 'NA'}}</td>


                        </tr>
                        <tr>
                            <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Email</th>
                            <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">{{$patient->email?? 'NA'}}</td>
                        </tr>
                        <tr>
                            <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Address</th>
                            <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">{{$patient->address?? 'NA'}}</td>
                        </tr>
                        <tr>
                            <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Contact</th>
                            <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">{{$patient->contact?? 'NA'}}</td>

                        </tr>

                        <tr>
                            <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Date of Birth</th>
                            <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">{{$patient->dob}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="col-lg-4">
                @if(!$patient->image)
                <div class=""><img src="{{asset('assets/svg/man-svgrepo-com.svg')}}" class="profile-photo" alt=""></div>
                @else
                <div class=""><img src="{{ asset('uploads/patients/'.$patient->image) }}" style="object-fit: cover;" class="profile-photo" alt=""></div>
                @endif
            </div>
        </div>

        <!-- Arrest Info -->
        <div class="section-title">Visitation & Appointment Info</div>
        <div class="table-responsive">
            <table class="table table-bordered align-middle">
                <thead class="table-light">
                    <tr>
                        <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Date</th>
                        <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Session Title</th>
                        <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Institution</th>
                        <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Doctor in-Charge</th>
                        <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Status</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">2018-10-05</td>
                        <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">Follow up</td>
                        <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">EBMC</td>
                        <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">Doctor Name</td>
                        <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">Finished</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- Fingerprints and Other Info -->
        <div class="row mt-3">
            <div class="col-md-6">
                <div class="section-title">Fingerprints</div>
                <div class="fingerprints d-flex flex-wrap">
                    <i class="fa fa-fingerprint"></i><i class="fa fa-fingerprint"></i><i class="fa fa-fingerprint"></i><i class="fa fa-fingerprint"></i><i class="fa fa-fingerprint"></i>
                </div>
            </div>
            <div class="col-md-6">
                <div class="section-title">Other Info</div>
                <p class="footer-note">
                    This has nothing to do with the health records. It's just something to fill up this area. Feel free to change it.
                </p>
            </div>
        </div>
    </div>


</div>

@endsection