@extends('layouts.app')
@section('title', 'Patient Update')
@section('content')
<div class="content-wrapper">
    <form action="{{route('patient_update', $patient->pid)}}" method="post">
        @csrf
        <div class="record-container" style="background-color: var(--outgoing-bg); color:var(--txt-color);">

            <!-- Header -->

            <div class="header-section d-flex justify-content-between align-items-start flex-wrap">
                <div>
                    <i class="fa fa-user-alt fa-3x"></i>
                    <div class="record-title">Update Patient Information</div>
                    <small>Made by Computer</small>

                </div>
                <div class="file-info mt-3 mt-md-0">
                    <p><strong>File Number:</strong> #1234567-890</p>
                    <p><strong>Record ID:</strong> E998A742</p>
                    <p><small>Generated by the State Computer</small></p>
                </div>

            </div>

            <!-- Personal Info -->
            <div class="row g-3">
                <div class="col-lg-8">
                    <table class="table table-borderless">
                        <tbody>
                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Name</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);"><input class="form-control" type="text" name="name" value="{{$patient->name}}" spellcheck="false"></td>
                            </tr>

                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Gender</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);"><select name="gender" id="gender" class="form-select" style="background-color: var(--outgoing-bg); color:var(--txt-color);">
                                        <option value="Male" {{ $patient->gender == 'Male' ? 'selected' : '' }}>Male</option>
                                        <option value="Female" {{ $patient->gender == 'Female' ? 'selected' : '' }}>Female</option>
                                    </select></td>
                            </tr>
                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Email</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);"><input class="form-control" type="email" name="email" value="{{$patient->email}}" spellcheck="false"></td>

                            </tr>
                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Contact</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);">
                                    <input class="form-control" type="tel" name="contact" maxlength="11" pattern="[0-9]{11}" value="{{$patient->contact}}" spellcheck="false">
                                </td>


                            </tr>
                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Address</th>
                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);"><textarea type="text" class="form-control w-100" name="address" rows="3" style="resize: none;" spellcheck="false">{{$patient->address}}</textarea></td>
                            </tr>
                            <tr>
                                <th style="background-color: var(--outgoing-bg); color:var(--txt-color);">Date of Birth</th>

                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);" colspan="3"><input class="form-control" type="date" name="dob" value="{{$patient->dob}}"></td>

                            </tr>
                            <tr>

                                <td style="background-color: var(--outgoing-bg); color:var(--txt-color);" colspan="5">

                                    <div class="section-title fw-bold text">Bio</div>
                                    <textarea name="biography" class="footer-note form-control text-start" rows="5">
                                    {{$patient->bio->biography ?? 'I am a dedicated and passionate student of this univerisity'}}
                                    </textarea>

                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="col-lg-4">
                    @if(!$patient->image)
                    <div class=""><img src="{{asset('assets/svg/man-svgrepo-com.svg')}}" class="profile-photo" alt=""></div>
                    @else
                    <div class=""><img src="{{ asset('uploads/patients/'.$patient->image) }}" style="object-fit: cover;" class="profile-photo" alt=""></div>
                    @endif
                </div>
            </div>

            <button class="btn btn-primary btn-lg">Update</button>

        </div>

        @if ($errors->any())
        <div class="text-center mt-4">
            @foreach ($errors->all() as $error)
            <p class="alert alert-danger">{{ $error }}</p>
            @endforeach
        </div>
        @endif
    </form>

</div>
@endsection